version: "3.1"

services:
  mariadb:
    image: mariadb
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 32768:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 32769:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - 32770:6379
  postgres:
    image: postgres
    ports:
      - 32771:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  cockroach:
    image: cockroachdb/cockroach
    ports:
      - 32772:26257
      - 8008:8080
    command: 
      - start 
      - --insecure
    volumes:
      - cdb-data:/cockroach/cockroach-data
  elastic:
    image: elasticsearch:7.7.1
    ports: 
      - 32774:9200
      - 32773:9300
    environment: 
      - discovery.type=single-node
    volumes: 
      - el-data:/usr/share/elasticsearch/data

volumes:
  sql-data:
  mongo-data:
  pg-data:
  cdb-data:
  el-data:
